/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <Platform_Types.h>

//Access to RCC Register
#define RCC_BASE  0x40021000
#define PORTA_BASE 0x40010800

#define RCC_APB2ENR	*(vuint32*)(RCC_BASE+0x18)
#define GPIOA_CRH   *(vuint32*)(PORTA_BASE+0x04)
#define GPIOA_ODR   *(vuint32*)(PORTA_BASE+0x0C)


typedef union
{
	vuint32  All_Pins;
	struct
	{
		vuint32 resrved:13;
		vuint32 Pin13:1;

	}Pin;

}Bit_Select;

volatile Bit_Select* ODR_Bit=(volatile Bit_Select*)(PORTA_BASE+0x0C);


int main(void)
{

	RCC_APB2ENR |= (1<<2);
	GPIOA_CRH  &=0xFF0FFFFF;
	GPIOA_CRH  |=0x00200000;

	while(1)
	{
		ODR_Bit->Pin.Pin13=1;
		for(int i=0;i<50000;i++);
		ODR_Bit->Pin.Pin13=0;
		for(int i=0;i<50000;i++);

	}


	return 0;
}
